######################################
# Available workflows, change value to
# true if you want to run that step
######################################
QC: True 
Assembly: False
Mapping: False
Binning: False

##########################################
# Basic options, These will be run before
# any of the above workflows. Change to True
# to run these steps
##########################################
working_dir: "./"

##########################################
# Workflow Params, Each Workflow has Options
# that can be initiated here. Defaults are 
# filled in below
##########################################
QC_Params:
  Merge_lanes: False
  Derep_reads: False
  input: ".test/fastqs.csv"
  extras:

Assembly_params:
  input:
  extras:

Mapping_params:
  input: "./mapping_input.yaml"
  extras: