######################################
# Available workflows, QC, Assembly,
# Mapping, Binning . Assign the one you
# want to run to mode
######################################
mode: 
##########################################
# Basic options, These will be run before
# any of the above workflows. Change to True
# to run these steps
##########################################
working_dir: "./"

##########################################
# Workflow Params, Each Workflow has Options
# that can be initiated here. Defaults are 
# filled in below
##########################################
QC_Params:
  csv_info: ".test/fastqs.csv"

Assembly_params:
  csv_info: ".test/assems.csv"
  scheme: "assembly_scheme.yaml"

Mapping_params:
  csv_info: ".test/mappings.csv"
  scheme: "mapping_scheme.yaml"

Binning_params:
  scheme: "binning_scheme.yaml"
