######################################
# Available workflows, 
# QC, Mapping, Assembly, Binning
# Change mode: to the above value you
# want to run
######################################
mode:

##########################################
# Basic options, These will be run before
# any of the above workflows. Change to True
# to run these steps
##########################################
working_dir: "./"


##########################################
# Workflow Params, Each Workflow has Options
# that can be initiated here. Defaults are 
# filled in below
##########################################
QC_Params:
  csv_info: "fastq_info.csv"

Assembly_Params:
  csv_info: "assembly_info.csv"
  scheme: "assembly_scheme.yaml"

Mapping_Params:
  csv_info: "mapping_info.csv"
  scheme: "mapping_scheme.yaml"

Binning_Params:
  scheme: "binning_scheme.yaml"
