######################################
# Available workflows, 
# QC, Mapping, Assembly, Binning
# Change mode: to the above value you
# want to run
######################################
mode: "Assembly"

##########################################
# Basic options, These will be run before
# any of the above workflows. Change to True
# to run these steps
##########################################
working_dir: "./"

##########################################
# Absolute paths to singularity containers
# Labeled for each software used by the
# workflow
##########################################
singularity:
 bbtools: "/nfs/turbo/lsa-dudelabs/containers/bbtools/bbtools.sif"
 bwa: "/nfs/turbo/lsa-dudelabs/containers/bwa/bwa.sif" #includes samtools in container
 checkm: "/nfs/turbo/lsa-dudelabs/containers/checkm/checkm.sif"
 concoct: "/nfs/turbo/lsa-dudelabs/containers/concoct/concoct_v1.1.0.sif"
 fastqc: "/nfs/turbo/lsa-dudelabs/containers/fastqc/fastqc.sif"
 megahit: "/nfs/turbo/lsa-dudelabs/containers/Megahit/megahit.sif"

##########################################
# Workflow Params, Each Workflow has Options
# that can be initiated here. Defaults are 
# filled in below
##########################################
QC_Params:
  csv_info: "fastq_info.csv"

Assembly_Params:
  csv_info: "assembly_info.csv"
  scheme: "assembly_scheme.yaml"

Mapping_Params:
  csv_info: "mapping_info.csv"
  scheme: "mapping_scheme.yaml"

Binning_Params:
  scheme: "binning_scheme.yaml"
