######################################
# Available workflows, change value to
# true if you want to run that step
######################################
QC: True 
Assembly: False
Mapping: False
Binning: False

##########################################
# Basic options, These will be run before
# any of the above workflows. Change to True
# to run these steps
##########################################
working_dir: "./"
container: "docker://continuumio/miniconda3:4.4.10"

##########################################
# Workflow Params, Each Workflow has Options
# that can be initiated here. Defaults are 
# filled in below
##########################################
QC_Params:
  csv_info: "fastq_info.csv"

Assembly_Params:
  csv_info: "assembly_info.csv"
  scheme: "assembly_scheme.yaml"

Mapping_Params:
  csv_info: "mapping_info.csv"
  scheme: "mapping_scheme.yaml"

Binning_Params:
  scheme: "binning_scheme.yaml"
